/**
 * Generates `virtual:flue/providers`, the provider-registration module shared
 * by the Node bootstrap and the generated Cloudflare Worker entry.
 *
 * With a configured `providers` list, only the listed
 * `@flue/runtime/providers/<id>` modules are imported — nothing else ships
 * in the build, and an unknown id fails the build at that import. Without
 * one, the default registers every built-in. Either way, IDs the user already registered (via `setProvider()`
 * in `app.ts`) are preserved.
 */

export function generateProvidersModule(providers: readonly string[] | undefined): string {
	if (providers === undefined) {
		return `// Auto-generated by @flue/vite. Do not edit.
import { registerDefaultProviders } from '@flue/runtime/internal';

registerDefaultProviders();
`;
	}

	// `cloudflare` names the Workers AI binding provider, which the generated
	// worker entry registers itself — not a built-in provider module.
	const ids = [...new Set(providers)].filter((id) => id !== 'cloudflare');
	if (ids.length === 0) {
		return `// Auto-generated by @flue/vite. Do not edit.
// No built-in providers are configured.
`;
	}
	const imports = ids.map(
		(id, index) =>
			`import * as __flue_provider_${index}__ from ${JSON.stringify(
				`@flue/runtime/providers/${id}`,
			)};`,
	);
	const registrations = ids.map(
		(id, index) =>
			`registerBuiltinProviderModule(${JSON.stringify(id)}, __flue_provider_${index}__);`,
	);
	return `// Auto-generated by @flue/vite. Do not edit.
import { registerBuiltinProviderModule } from '@flue/runtime/internal';
${imports.join('\n')}

${registrations.join('\n')}
`;
}
